server:
  port: 8084

eureka:
    instance:
        appname: fpla-gendb
        instanceId: fpla-gendb:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: fpla-gendb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/fplagendb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;DATABASE_TO_UPPER=true
    name:
    username: fpla
    password:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false
